name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GH secret
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Plugins
          user: Dwigoric
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          repositories_affiliations: owner, collaborator, organization_member
          plugin_introduction: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_activity: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          plugin_skyline: yes
          plugin_sponsors: yes
          plugin_stars: yes
          plugin_traffic: yes
          
          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: ${{ secrets.COMMIT_AUTHOR_LIST }}
          plugin_languages_details: lines
          plugin_languages_sections: recently-used, most-used
